### ISSUE TITLE
chore: Create .env.example

### ISSUE THREAD

**Issue by chair28980** [waku-org/nwaku-compose#37]
## Problem

Currently users are not explicitly provided instructions to save their environment variables in a specific location.

## Tasks
- [ ] Create .env.example file template with required values
- [ ] include .env in .gitignore file
- [ ] Update issue in https://github.com/waku-org/docs.waku.org/issues/154 docs.waku.org repo to indicate changes are ready for documentation

**Comment by fryorcraken** [comment]
isn't it done? I saw a `.env.example` in my checkout. @vpavlin ?

**Comment by fryorcraken** [comment]
https://github.com/waku-org/nwaku-compose/blob/master/.env.example

**Comment by chair28980** [comment]
Correct, this is already merged, I referenced only my local branch which is missing the .env.example :blush:
